# Generated by Django 4.2.20 on 2025-05-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_data_fotografia_fotografia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='data_fotografia',
        ),
    ]
